from typing import Dict, List, Any
from github import Github, GithubException
from config import Config

class PRCommenter:
    """Handles posting comments on GitHub Pull Requests"""
    
    def __init__(self):
        self.github = Github(Config.GITHUB_TOKEN)
    
    def post_review(self, pr_info: Dict[str, Any], review_results: List[Dict[str, Any]]) -> bool:
        """
        Post a complete review on a pull request
        
        Args:
            pr_info: PR information dictionary
            review_results: List of analysis results per file
            
        Returns:
            True if successful, False otherwise
        """
        try:
            repo = self.github.get_repo(pr_info['repo_full_name'])
            pr = repo.get_pull(pr_info['pr_number'])
            
            # Prepare review comments
            comments = []
            summary_parts = []
            
            for result in review_results:
                file_path = result['file']
                
                # Add inline comments for issues
                for issue in result.get('all_issues', []):
                    if issue.get('line', 0) > 0:
                        comment = self._format_inline_comment(issue)
                        comments.append({
                            'path': file_path,
                            'line': issue['line'],
                            'body': comment
                        })
                
                # Add to summary
                if result.get('summary', {}).get('total_issues', 0) > 0:
                    summary_parts.append(
                        f"**{file_path}**: {result['summary']['total_issues']} issues found"
                    )
            
            # Create review summary
            summary = self._create_review_summary(pr_info, review_results, summary_parts)
            
            # Post review
            if comments:
                pr.create_review(
                    body=summary,
                    event='COMMENT',
                    comments=comments[:30]  # GitHub API limit
                )
            else:
                # Post as regular comment if no inline comments
                pr.create_issue_comment(summary)
            
            return True
            
        except GithubException as e:
            print(f"Error posting review: {e}")
            return False
    
    def post_inline_comment(self, pr_info: Dict[str, Any], file_path: str, 
                           line: int, comment: str) -> bool:
        """
        Post a single inline comment on a PR
        
        Args:
            pr_info: PR information
            file_path: File path
            line: Line number
            comment: Comment text
            
        Returns:
            True if successful
        """
        try:
            repo = self.github.get_repo(pr_info['repo_full_name'])
            pr = repo.get_pull(pr_info['pr_number'])
            commit = repo.get_commit(pr_info['head_sha'])
            
            pr.create_review_comment(
                body=comment,
                commit=commit,
                path=file_path,
                line=line
            )
            
            return True
            
        except GithubException as e:
            print(f"Error posting inline comment: {e}")
            return False
    
    def _format_inline_comment(self, issue: Dict[str, Any]) -> str:
        """Format an issue as an inline comment"""
        severity_marker = {
            'high': '[HIGH]',
            'medium': '[MEDIUM]',
            'low': '[LOW]',
            'info': '[INFO]'
        }
        
        marker = severity_marker.get(issue.get('severity', 'medium'), '[ISSUE]')
        category = issue.get('category', issue.get('type', 'issue'))
        message = issue.get('message', 'No description')
        suggestion = issue.get('suggestion', '')
        auto_fix = issue.get('auto_fix', '')
        
        comment = f"{marker} **{category.upper()}** ({issue.get('severity', 'medium')})\n\n"
        comment += f"{message}\n\n"
        
        if suggestion:
            comment += f"**Suggestion:** {suggestion}\n\n"
        
        if auto_fix:
            comment += f"**Auto-fix:**\n```python\n{auto_fix}\n```\n\n"
        
        comment += "*Generated by X-code AI Code Review Assistant*"
        
        return comment
    
    def _create_review_summary(self, pr_info: Dict[str, Any], 
                               review_results: List[Dict[str, Any]],
                               summary_parts: List[str]) -> str:
        """Create a review summary comment"""
        total_issues = sum(r.get('summary', {}).get('total_issues', 0) for r in review_results)
        
        summary = f"## X-code AI Code Review\n\n"
        summary += f"**PR:** {pr_info['pr_title']}\n"
        summary += f"**Author:** @{pr_info['author']}\n"
        summary += f"**Files Reviewed:** {len(review_results)}\n"
        summary += f"**Total Issues Found:** {total_issues}\n\n"
        
        if total_issues > 0:
            summary += "### Summary by File\n\n"
            summary += "\n".join(summary_parts)
            summary += "\n\n"
            summary += "### Issue Breakdown\n\n"
            
            # Count by severity
            severity_counts = {'high': 0, 'medium': 0, 'low': 0}
            for result in review_results:
                for issue in result.get('all_issues', []):
                    sev = issue.get('severity', 'medium')
                    if sev in severity_counts:
                        severity_counts[sev] += 1
            
            summary += f"- High: {severity_counts['high']}\n"
            summary += f"- Medium: {severity_counts['medium']}\n"
            summary += f"- Low: {severity_counts['low']}\n\n"
        else:
            summary += "No issues found! Great work!\n\n"
        
        summary += "---\n"
        summary += "*Powered by Groq Llama 3.3 70B + Static Analysis Tools*"
        
        return summary